VFX_DICT = {
    "ROBO": [
        "phosphorous",
        "sulphurous",
        "memory leak",
        "overclocked",
        "electrostatic",
        "power surge",
        "anti-freeze",
        "roboactive",
        "time warp",
        "green black hole",
    ],
    "EOTL": [
        "molten mallard",
        "morning glory",
        "death at dusk",
        '"Unusual Effect: Frostbite"',
    ],
    "SFXIII": [
        "pumpkin moon",
        "viridescent peeper",
        "eyes of molten",
        "ominous stare",
    ],
    "SFX": [
        "galactic gateway",
        "the eldritch opening",
        "the dark doorway",
    ],
    "SFVII": ["eldritch flame", "ancient eldritch", '"death by disco"'],
    "BONZO": [
        '"bonzo the all-gnawing"',
        "amaranthine",
        "stare from beyond",
        "the ooze",
        "ghastly ghosts jr",
        "haunted phantasm jr",
    ],
    "ARCANA": [
        "arcana",
        '"Unusual Effect: Spellbound"',
        "chiroptera venenata",
        "poisoned shadows",
        "something burning this way comes",
        "hellfire",
        "darkblaze",
        "demonflame",
    ],
    "MOONS": [
        "knifestorm",
        "misty skull",
        "harvest moon",
        "it's a secret to everybody",
        "stormy 13th hour",
    ],
    "EERIE": [
        "flaming lantern",
        "cloudy moon",
        "cauldron bubbles",
        "eerie orbiting fire",
    ],
    "NSTORMS": [
        "Acidic Climate",
        "Otherworldly Weather",
        "Nightmarish Storm",
        "Celestial Summit",
        "Stellar Ascent",
    ],
    "TAUNT": ["ominous night", "spooky night", "charged arcane"],
}

UNUS_COLS = ["unusual_effect", "name", "sell_price_text"]
